init_pose:
  l_ank_pitch: 0.625
  l_ank_roll: 0.016
  l_hip_pitch: -0.828
  l_hip_roll: 0.016
  l_hip_yaw: 0.00
  l_knee: 1.192
  l_sho_pitch: 0.00
  l_sho_roll: 1.293
  l_el_pitch: -0.10
  l_el_yaw: -1.926
  l_gripper: 0.00
  r_ank_pitch: -0.625
  r_ank_roll: -0.016
  r_hip_pitch: 0.828
  r_hip_roll: -0.016
  r_hip_yaw: 0.00
  r_knee: -1.192
  r_sho_pitch: 0.00
  r_sho_roll: -1.293
  r_el_pitch: 0.10
  r_el_yaw: 1.926
  r_gripper: 0.00
  head_pan: 0.00
  head_tilt: 0.00
